// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsWINWaIHuCa1ndEMCRSyjxUTKoAwtR4',
    appId: '1:1070540278752:web:015af26a2219ee294e7985',
    messagingSenderId: '1070540278752',
    projectId: 'isenecakk',
    authDomain: 'isenecakk.firebaseapp.com',
    storageBucket: 'isenecakk.appspot.com',
    measurementId: 'G-9BK6GV8F7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBmfk42dV_JRARcqD7heM_nAcFWOZ40S8',
    appId: '1:1070540278752:android:537490c69f03e1324e7985',
    messagingSenderId: '1070540278752',
    projectId: 'isenecakk',
    storageBucket: 'isenecakk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Q0Nga3YqMIOniexP5OBRbBMWEbglLdY',
    appId: '1:1070540278752:ios:b1760e973a2d7f5d4e7985',
    messagingSenderId: '1070540278752',
    projectId: 'isenecakk',
    storageBucket: 'isenecakk.appspot.com',
    iosClientId: '1070540278752-nrsvpipunal7k8409mdb5qqlne4hse8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGoogleSignInTutorial',
  );
}
